[package]
name = "foxpaw-habanero"
version = "0.1.0"
edition = "2024"

[dependencies]

[lib]
name="habanero"
path="src/lib.rs"

[lints.clippy]
cargo = "deny"
correctness = "deny"
pedantic = "deny"
perf = "deny"
style = "deny"
suspicious = "deny"